//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string book_id { get; set; }
        public string room_id { get; set; }
        public string people_pax { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string guest_id { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
