//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public string task_id { get; set; }
        public string room_id { get; set; }
        public string task_time { get; set; }
        public string task_date { get; set; }
        public string staff_id { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
