//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string payment_id { get; set; }
        public string guest_id { get; set; }
        public string card_no { get; set; }
        public string holder_name { get; set; }
        public string card_expiry { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
